version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: trello-postgres
    restart: unless-stopped
    ports:
      - "51213:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trello_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:







